<?php
    $diccionary = array(
        'Love' => 'Amor',
        'Friend' => 'Amigo',
        'Sun' => 'Sol',
        'Moon' => 'Luna',
        'Star' => 'Estrella',
        'Tree' => 'Árbol',
        'Water' => 'Agua',
        'Fire' => 'Fuego',
        'Earth' => 'Tierra',
        'Sky' => 'Cielo',
        'Dream' => 'Sueño',
        'Life' => 'Vida',
        'Death' => 'Muerte',
        'Peace' => 'Paz',
        'War' => 'Guerra',
        'Light' => 'Luz',
        'Shadow' => 'Sombra',
        'Hope' => 'Esperanza',
        'Fear' => 'Miedo',
        'Bird' => 'Pájaro',
        'Mountain' => 'Montaña',
        'Ocean' => 'Océano',
        'Rain' => 'Lluvia',
        'Wind' => 'Viento',
        'Smile' => 'Sonrisa',
        'Heart' => 'Corazón',
        'Flower' => 'Flor',
        'Snow' => 'Nieve',
        'Stone' => 'Piedra',
        'Freedom' => 'Libertad'
    );
?>